- faq.md
> update shell-in steps after merge of openshift-spark#21

- faq.md
> add login failure to faq

- get-started.md
- resources.yaml
> add global resources.yaml to help install/setup and update getting started to use it

- faq.md
> no need to cd w/ new WORKDIR in openshift-spark

- resources.yaml
> attribute the pyspark-build-dc template openshift console display properties

- resources.yaml
> Add service to pyspark-build-dc

- resources.yaml
> add app=APPLICATION_NAME to pyspark-build-dc resources

- _applications/grafzahl.md
> use new service and consistent labeling

- _applications/grafzahl.md
> use APP_ARGS instead of env to pass bootstrap.servers

- resources.yaml
> remove unnecessary label and fix case for service-pod association in the openshift console

- _projects/oshinko.md
This change removes the core project and adds language to the cli
project to mention the core and rest aspects.
> update oshinko project language

- _applications/amqpstreaming.md
- _applications/grafzahl.md
- _applications/ophicleide.md
- _applications/var.md
- tutorials.md
> add weight to apps to enable sorted display

- _templates/example_application.md
@elmiko ptal, forgot this in last PR
> provide default app weight in template

- _includes/analytics.html
- _layouts/default.html
> add google analytics

- _applications/s3-source-example.md
> fix link to s3 source example ipynb file

- CONTRIBUTING.md
- Dockerfile
- _config.yml
This change adds a dockerfile and instructions for using it during local
testing.
> add a Dockerfile for convenience

- _layouts/application.html
- _layouts/default.html
- _layouts/markdown.html
- index.html
- projects.html
This change combines several small adjustments to improve access by mobile devices. The main improvements are adding the proper meta tags to detect device size, adding column class data to help with medium and larger size screens, adding the javascript components for the navbar, and some cleanup to the applications template.
> Improve mobile access

- _includes/menu_tutorial_application.html
This change adds a link to the applications menu which links back to the
tutorials page.
> add a menu item back to the tutorials

- _applications/pyspark_hdfs_notebook.md
- bower.json
- get-started.md
This just changes the internal references to explicitly add the https
scheme to any site references. Also adjusted the get-started reference
in the hdfs notebook doc.
> update http references to https

- _data/presentations.yaml
This is the talk from Red Hat Summit 2017
> add talk by Steve Pousty and Michael McCune

- _data/presentations.yaml
this commit adds Erik's Spark Summit SF talk and my Berlin Buzzwords talk
> added presentations from June

- resources.yaml
This adds the resources necessary to run scala based s2i applications
to the resources.yaml file.
> add scala s2i template to resources.yaml

- CONTRIBUTING.md
- Gemfile
- Gemfile.lock
- _config.yml
- _faqs/how-to-connect-to-cluster.adoc
- _faqs/how-to-connect-to-cluster.md
- _faqs/how-to-connect-to-kafka.adoc
- _faqs/why-am-i-getting-ioexception.adoc
- _faqs/why-am-i-getting-ioexception.md
- _templates/example_faq.adoc
- _templates/example_faq.md
* add jekyll-asciidoc plugin to dependencies
* convert faq markdown files into asciidoc files
* add output to faq collection
* update some jekyll dependencies
* update documentation and examples
> add poc for faqs in asciidoc format

- Gemfile
- Gemfile.lock
The absence of json was causing issues in the container build.
> add json to gemfile

- css/radanalytics.css
- index.html
To the individual pages associated with each text blurb. Also add some
styling to keep the look the same.
> add links from the front page

- _includes/gh_star.html
- _projects/openshift-spark.adoc
- _projects/oshinko.adoc
- _projects/scorpion-stare.adoc
- _projects/silex.adoc
- _projects/spark-amqp-connector.adoc
Well, it's still needed to click on the star on the github page. There is also option to show the star counter.
> Adding clickable buttons that can give us a star

- _presentations/probabilistic-structures.adoc
This commit adds slides and a video (such as it is) of Will's talk at DevConf.cz.
> Add Will's DevConf.cz presentation

- CONTRIBUTING.md
- _config.yml
- _data/menu.yaml
- _howdoi/how-to-connect-to-cluster.adoc
- _howdoi/how-to-connect-to-kafka.adoc
- _layouts/default.html
- _templates/how-do-i.adoc
- css/radanalytics.css
- how-do-i.html
Changes
* add howdoi to config
* add howdoi to menu
* add howdoi template
* remove how to faqs
* add how to from faqs to howdoi
* change default layout to add list expansion code
> add how do i page

- resources.yaml
which was fixed in this version to reduce the number of clicks to login.
> Bumping up version of oauth-proxy and using --skip-provider-button

- resources.yaml
Just tweaking a few metadata values and keys to be consistent between
the various templates.
> adjust resources.yaml for consistency

- _applications/project-jiminy.adoc
This deck is still being constructed, it will be re-added when ready.
> remove lightning talk menu entry for jiminy

- _applications/grafzahl.adoc
- _applications/project-jiminy.adoc
- _applications/wine-map.adoc
- _howdoi/how-to-connect-to-kafka.adoc
- assets/my-first-radanalytics-app/sparkpi-python-flask.adoc
- resources.yaml
this change makes the python template follow the java and scala template
names more closely.
> change python template name

- _applications/wine-map.adoc
This just makes the commands easier to read on smaller screens.
> refactor winemap examples to use multiline

- _applications/jgrafzahl.adoc
this is to support the latest spark version
> update dependency version on jgrafzahl

- .gitignore
this change helps to ensure that no one will commit bundle related files
into the repo.
> update ignore file

- assets/my-first-radanalytics-app/sparkpi-java-vertx.adoc
- my-first-radanalytics-app.adoc
Code examples for Java SparkPi with Vert.x
> Add SparkPi Vert.x examples

- assets/my-first-radanalytics-app/sparkpi-python-flask.adoc
This brings the `oc new-app` command more in line with the other
tutorials.
> update link in sparkpi python flask example

- community.html
Fixed comma splice; added number agreement for technologies; other minor tweaks.
> minor editing to community page prose

- _howdoi/validate-radanalytics-install.adoc
- assets/tools/rad-validate
This change adds a script for validating that the resource.yaml has been
installed properly. It also contains an article describing how to use
the script.
> add rad-validate tool and how do i article

- _applications/grafzahl.adoc
- _applications/jgrafzahl.adoc
Change Strimzi template in order to use ephemeral Kafka in Grafzahl and jGrafzahl
> Change Strimzi to use ephemeral Kafka (Grafzahl/jGrafzahl)

- _howdoi/launch-jupyter-notebook.adoc
- _howdoi/use-python-packages.adoc
- _howdoi/use-python3-with-spark.adoc
some of the how do I questions didn't end in a question mark. Others did. I added question marks to all questions.
> added question marks to end of questions

- _presentations/from-research-to-production.adoc
Added my Berlin Buzzword Talk to presentations
> B buzz talk

- assets/my-first-radanalytics-app/sparkpi-java-vertx.adoc
Sparkpi-vertx updated due to https://github.com/radanalyticsio/tutorial-sparkpi-java-vertx/commit/e5dc64e5e593204721263daee0997588a74279d7
> Update sparkpi-vertx tutorial in light of app changes

- _applications/project-jiminy.adoc
The tutorial now has the extra logging steps which were added to the code in jiminy-data-loader
> Added extra logging steps to 'expected output'

- _applications/grafzahl.adoc
- _applications/jgrafzahl.adoc
- _applications/ophicleide.adoc
- _applications/project-jiminy.adoc
- _applications/tensorflow_mnist.adoc
- _applications/wine-map.adoc
- _examples/amqpstreaming.adoc
- _examples/apache-zeppelin-example.adoc
- _examples/blockchain.adoc
- _examples/ceph-source-example.adoc
- _examples/fabric8-maven-plugin.adoc
- _examples/pyspark_hdfs_notebook.adoc
- _examples/s3-source-example.adoc
- _examples/var.adoc
- _includes/menu_tutorial_application.html
- _layouts/application.html
- tutorials.md
this change adds longer titles to the tutorial applications. it also adds some metadata to the tutorial files and some minor changes to the visual layout of the tutorials page.
do not merge before #242
> Add application titles

- _examples/amqpstreaming.adoc
- _examples/apache-zeppelin-example.adoc
- _examples/blockchain.adoc
- _examples/ceph-source-example.adoc
- _examples/fabric8-maven-plugin.adoc
- _examples/pyspark_hdfs_notebook.adoc
- _examples/s3-source-example.adoc
- _examples/var.adoc
This change will make it easier to understand what topic areas the
examples are addressing.
> update the tutorial example titles

- _howdoi/use-spark-configs.adoc
Changed the `oc` command to `oshinko` instead.
> fix how do i use spark configs

- community.html
Added per-year presentation headers; moved metadata to disclosed content.
> minor community redesign

- _templates/application_or_example.adoc
This value is now required for applications and examples.
> add page-project-name to application template

- _applications/jgrafzahl.adoc
A fix for a vulnerability report has been merged in the upstream
jgrafzahl source, this change reflects the updated package in the spark
submit command for the tutorial.
> update launch command for jgrafzahl
