radanalyticsio/radanalyticsio.github.io

_includes/menu_tutorial_application.html
This replaces the hardcoded value with the proper variable from the page
front matter.
closes issue #4
=> add missing variable to lighting link

CONTRIBUTING.md
This adds a small paragraph to the contributing doc about issues that
may come up while installing the site gems on Mac OSX.
Also a minor fix to the title of the contributing doc.
=> add specific info about osx devel

faq.md
This change removes the bold and italics markdown in favor of using the
code literal blocks. Also adds a sentence and moves the example command
into a code block.
=> clean up the markdown in the kafka question

_applications/ophicleide.md
This change updates the oshinko installation instructions for the
ophicleide tutorial. It now references the "Get Started" page for a
simple set of installation instructions.
closes issue #32
=> update ophicleide docs

resources.yaml
This change adds the template for the java s2i builder deployment config
template. It copies the python template and then replaces values with
the upstream java template from the s2i repository.
closes #31
=> add the java spark build dc template to resources

resources.yaml
This change is to allow java jar files that specify their own boot
information. For example, springboot created jars do not work well with
the APP_MAIN_CLASS, but do work well with APP_FILE.
=> change APP_MAIN_CLASS requirement to false

_applications/spring_sparkpi.md
This change adds a short video showing the deployment and usage of the
spring boot sparkpi tutorial.
=> add a video demonstration to spring sparkpi

_config.yml
This change is to prune some of the non-necssary files from the jekyll
deployment.
=> add files to the exclude in _config.yml

_layouts/default.html
This change adds a button that links to the project site on github. This
button appears in the utility navbar across the top and will be hidden
on mobile devices to avoid messing with the menu.
=> add an edit me on github button

_layouts/markdown.html, projects.html
This change is to improve usability on tablets. Previously the medium
size columns were making the content render off screen, now the content
will render properly on tablet size devices.
=> change col-md to col-lg

CONTRIBUTING.md, _applications/amqpstreaming.md, _applications/fabric8-maven-plugin.md, _applications/grafzahl.md, _applications/jgrafzahl.md, _applications/ophicleide.md, _applications/pyspark_hdfs_notebook.md, _applications/s3-source-example.md, _applications/spring_sparkpi.md, _applications/var.md, _includes/menu_tutorial_application.html, _templates/example_application.md
This change adds the menu_items front matter to the applications
markdown. The menu_items allows for custom definition of which links
should appear in the tutorial application menu. Currently the only
supported option in `lightning`, for the lightning talk slide deck. This
change also adds some documentation about how menu_items works.
=> add menu_items to application markdown

resources.yaml
This change standardizes the language in the description field for the
embedded templates in resources.yaml, instead of using the abbreviations
"S2I" or "STI" it is non expanded to "source-to-image".
=> change STI and S2I in descriptions

_applications/amqpstreaming.md, _applications/fabric8-maven-plugin.md, _applications/grafzahl.md, _applications/jgrafzahl.md, _applications/ophicleide.md, _applications/pyspark_hdfs_notebook.md, _applications/s3-source-example.md, _applications/spring_sparkpi.md, _applications/var.md, _projects/openshift-spark.md, _projects/oshinko.md, _projects/scorpion-stare.md, _projects/silex.md, _projects/spark-amqp-connector.md, _templates/example_application.md, projects.html, tutorials.md
This change adds labels for the tutorial applications and projects. The labels are implemented as front matter for each markdown document. The labels are displayed as badges next to the titles in the tutorials and projects pages.
this closes #48
=> Add labels

resources.yaml
The s2i scripts want information from the downward api about
the pod and deployment. Include the pod name as an env var
and the label set as a volume.
=> Add downward api items to resources.yaml

get-started.md
For some users, minishift is the easiest path to start using OpenShift.
The get-started doc now references it directly.
=> add minishift to the get-started page

resources.yaml
There are cases where the main class is not required, this should not
prevent a user from creating a spark s2i applicaiton.
=> remove required main class for scala s2i

_applications/var.md
This removes some of the old image names and deprecated workflow references in the VaR tutorial.  It still relies on a custom worker image, although it uses the notebook itself as that image (to minimize potential mismatches).
=> updated VaR tutorial

Gemfile, Gemfile.lock
The minima theme is not used by the project and is being removed to help
clean up the install process.
=> remove minima dependency

_applications/spring_sparkpi.adoc
=> Fix a broken link in spring_sparkpi.adoc

_applications/ophicleide.adoc
This fixes a bad markup tag in the asciidoc.
=> correct link to ophicleide setup list

_examples/var.adoc
The new VaR screencast uses current deployment methods, includes some of the
distribution exploration from the workshop, and has a voiceover that doesn't clip.
=> Update VaR screencast embed and link.

.travis.yml
This change adds travis tests which check whether or not
resources.yaml in the current pull request or branch differs
from resources.yaml on the master branch. If resources.yaml
is different, the template integration tests from the oshinko-s2i
repository are run against the templates created by resources.yaml.
If resources.yaml is not different, the test returns success.
=> Add integration tests for changes to resources.yaml

_applications/ophicleide.adoc, css/radanalytics.css
This change adds some command line instructions to the ophicleide
tutorial. These instructions are fashioned in the cut-paste style of the
other tutorials but with added content block styling to help them flow
with the document.
changes
* add quickstart instruction to ophicleide
* add css styling for content blocks
=> add command line quickstarts to ophicleide

resources.yaml
Recent changes in oshinko components move the default spark image
value into the various images/binaries so that known spark versions
can easily be associated with tagged images and release tarballs.
Accordingly, the webui template included in resources.yaml should
not set an explicit spark image override here.
=> Remove default OSHINKO_CLUSTER_IMAGE setting in resources.yaml

resources.yaml
This change would allow radanalyticsio to control tagging
in docker and have resources.yaml track released images
approved and tagged as "stable" instead of "latest".
=> Modify resources.yaml to reference "stable" tag on images

get-started.md
This change adds simple instructions to generate and process
a modified resources.yaml from https://radanalyticsio/resources.yaml
that uses s2i and oshinko-webui images from a particular Oshinko
release.
=> Add alternative instructions for using a specific Oshinko release

resources.yaml
After some review it looks like there is further work to be done before
the resources.yaml changes from PR #115 can be fully accepted. This
patch reverts the resources.yaml file to its previous state.
=> revert pull request 115

_applications/spring_sparkpi.adoc, assets/spring_sparkpi/lightning/index.html
The code repository has been moved to tutorial-sparkpi-java-spring to
help align it with the other sparkpi applications. This is to accomodate
the upcoming "my first app" tutorial.
=> update repo links for sparkpi-spring

README.md
Adding a sentence to `README.md` (that is displayed on github by default) about the `CONTRIBUTING.md`.
I missed the `CONTRIBUTING.md` file because there is a lot of other other files in the root directory. However, all the useful information is in this file, so I think it deserves the link from the `README.md`.
=> minor: Update to README.md

CONTRIBUTING.md, _includes/copy_button.html, _layouts/default.html, bower.json, get-started.md
This is how it looks like on Chrome:
Usage:
* from adoc:
1. add `:page-liquid:` header
2. 
```bash
+++{% include copy_button.html lang='bash' text='
<code goes here>
'%}+++
```
* from markdown:
```bash
{% include copy_button.html lang='bash' text='
<code goes here>
'%}
```
If argument `lang` is not specified, it defaults to 'bash'.
=> Adding new liquid template for code snippets that can be copy&pasted

assets/my-first-radanalytics-app/sparkpi-java-spring.adoc
The tutorial for the sparkpi java spring application contained a
mismatch in class names for the spark context provider. This change
fixes the mismatch in names.
=> fix class name for SparkPiContextProvider

assets/my-first-radanalytics-app/sparkpi-java-spring.adoc, assets/my-first-radanalytics-app/sparkpi-python-flask.adoc
The return links at the bottom of the java and python tutorials were not
set properly. This change corrects the links and points them to the user
section of the my first app main tutorial page.
=> fix links in my first app tutorials

.gitignore
Just to ensure that we do not check in a directory full of bower
dependencies.
=> add bower folder to ignore file

_applications/grafzahl.adoc, _applications/wine-map.adoc, _howdoi/how-to-connect-to-kafka.adoc, assets/my-first-radanalytics-app/sparkpi-python-flask.adoc, resources.yaml
This change brings parity to the build-dc templates that exist within
the resources.yaml manifest. It also updates individual tutorials and
documentation that referred to the older `oshinko-pyspark-build-dc`
templates.
=> update resources.yaml file

Dockerfile
The website can now be served using the docker build command on mac.
=> Changed ownership for user 1001

_presentations/from-notebooks-to-cloud-native.adoc
This adds the slidedeck link for the "from notebook to cloud native"
talk.
=> add slide deck link to strata talk

CONTRIBUTING.md
Since in Linux, `chmod` can take both `[arg] mode file` and `mode [arg] file` but macOS' `chmod` only accepts `[arg] mode file`, the instructions on `CONTRIBUTING.md` were changed to work in both OSes.
=> Changed `chmod` argument order for macOS compatibility

openshift/README.md
Double spaces (or another mechanism) are needed for reliable
line breaks in markdown files.
=> Fix line breaks in openshift/README.md

resources.yaml
The templates must create a headless service and set the URL
for the driver host in order for workers to contact the driver
when using Spark 2.3. These changes are backwards compatible
to spark 2.2 and 2.1 based on testing.
=> Modify resources.yaml for Apache Spark 2.3 support

_howdoi/how-to-connect-to-kafka.adoc
The version in the example is `2.1.0`, this change adds a warning note
to the user about the need to change this value when using different
Spark versions.
=> add note about version info to kafka how do i

_applications/grafzahl.adoc, _applications/jgrafzahl.adoc
Update Grafzahl and jGrahzahl instructions to use Strimzi's provided Kafka instead of `mattf/openshift-kafka`.
=> Change Kafka instructions to use Strimzi

CONTRIBUTING.md
This change adds the instructions on using bower during the development
process. Bower is needed to install some of the css and javascript
dependencies.
=> add bower to instructions

assets/my-first-radanalytics-app/sparkpi-java-spring.adoc, assets/my-first-radanalytics-app/sparkpi-python-flask.adoc
The link back to the instructions was based on a previous version of the
site layout. This change corrects that.
=> fix link in sparkpi tutorials

assets/my-first-radanalytics-app/sparkpi-java-spring.adoc
Changed tutorial so that the SparkPi Spring example code is consistent with the [repository](https://github.com/radanalyticsio/tutorial-sparkpi-java-spring/blob/master/src/main/java/io/radanalytics/SparkContextProvider.java)
=> Make SparkPi Spring tutorial consistent with repo code

assets/my-first-radanalytics-app/sparkpi-java-spring.adoc
This updates the spark version to 2.3.0 in the spring sparkpi tutorial
to match the current version of oshinko spark tooling.
=> update spark version in spring tutorial

Gemfile, _config.yml, _howdoi/use-python-packages.adoc
Use coderay and inline styles for syntax highlighting; these options apparently need to be specified in document headers (and not in `_config.yml`).
This commit also corrects asciidoc code block syntax in the `pip install` "How do I?" post.
=> Use coderay for syntax highlighting.

_presentations/probabilistic-structures.adoc, _templates/presentation.adoc, community.html
This PR publishes date information for all talks and adds additional optional presentation metadata to capture the presentation venue, the city it was held in, and any handout (in addition to slides).
=> Additional metadata for community presentations

_data/menu.yaml
The menu title was incorrect and included an uppercase character that
was throwing off the detection script.
=> fix error in how do i menu

_config.yml, _howdoi/how-do-i-launch-a-jupyter-notebook.adoc, _howdoi/how-do-i-recognize-version-clash.adoc, _howdoi/how-to-connect-to-cluster.adoc, _howdoi/how-to-connect-to-kafka.adoc, _howdoi/how-to-use-spark-configs.adoc, _howdoi/use-python-packages.adoc, _layouts/howdoi.html, _templates/how-do-i.adoc, css/radanalytics.css, how-do-i.html
this change brings in individual page links for each "how do i" article. it also moves each article to its own page. additionally, the link from the jupyter python package installation article has been updated with a link to the jupyter article.
=> Add howdoi links

_includes/menu_radanalytics.html
This change makes the menu links always point back to their full url.
Previously the "current" page would redirect to a blank url with the
intent of reducing a reload to the same page. This turned out to make
poor usability for the "how do i" links.
=> fix standard menu links

_applications/ophicleide.adoc, assets/ophicleide/ophicleide-setup-list.yaml
With the change to spark 2.3+, the ophicleide application is having
issues connecting to an external spark cluster. This change will add the
necessary bits for the spark workers to communicate back to the master.
Additionally, an update was made to the ophicleide-training service to
support the new environment variable.
=> add updates to ophicleide manifest

resources.yaml
The only difference is the command issued at start time.  After this change, we will no longer need to maintain a separate image for the oc-proxy container.
=> Changes to have the oc-proxy container use the same image as the webui.

_applications/wine-map.adoc
This change removes the `OSHINKO_CLUSTER_NAME` parameter from the
winemap tutorial. This parameter is not mentioned in the instructions
and is not needed for the s2i deployment of the application.
=> remove cluster name from winemap install

resources.yaml
This change revises the openshift displayed name and descriptions for
the oshinko webui pods. It is mainly cosmetic to make the project
catalog a little cleaner.
=> update descriptions for oshinko pods

_data/menu.yaml, assets/my-first-radanalytics-app/sparkpi-java-spring.adoc, assets/my-first-radanalytics-app/sparkpi-java-vertx.adoc, assets/my-first-radanalytics-app/sparkpi-python-flask.adoc, my-first-radanalytics-app.adoc, tutorials.md
This change is moving the my first application tutorial to make it more
consistent with the other tutorial content on the site. It has been
observed that even experienced users miss the navbar entry for this
tutorial.
changes
* remove my first app from menu
* change titles in my first app to read better
* add project titles to sparkpi impl docs
=> move my first application into tutorials page

_howdoi/access-advanced-config-oshinko-webui.adoc, _howdoi/deploy-a-spark-cluster-webui.adoc
This change adds the new article for the advanced cluster config "how do i", and updated the basic oshinko webui deploy "how do i" with a link to the new document.
Do not merge before #247
=> Add advanced config oshinko webui

_howdoi/deploy-a-spark-cluster-cli.adoc, _howdoi/install-oshinko-cli.adoc
This change adds the new how do i article for deploying a cluster with
oshinko-cli. It also updates links and the title of the oshinko-cli
install how do i article.
=> add article on deploying spark with oshinko cli

_howdoi/access-advanced-config-oshinko-webui.adoc, _howdoi/access-spark-webui.adoc, _howdoi/connect-to-cluster.adoc, _howdoi/connect-to-kafka.adoc, _howdoi/deploy-a-spark-cluster-cli.adoc, _howdoi/deploy-a-spark-cluster-webui.adoc, _howdoi/install-oshinko-cli.adoc, _howdoi/launch-jupyter-notebook.adoc, _howdoi/recognize-version-clash.adoc, _howdoi/use-python-packages.adoc, _howdoi/use-python3-with-spark.adoc, _howdoi/use-spark-configs.adoc, _howdoi/validate-radanalytics-install.adoc, _layouts/howdoi.html, _templates/how-do-i.adoc, how-do-i.html
Previously, the how do i articles all assumed that a writer would create
a title that did not include the "How do I" preamble. This resulted in
document titles that looked incomplete and poorly formed. This change
makes it so that the individual article titles must include the full
sentence including "How do I" at the beginning.
=> fix titles in how do i articles

my-first-radanalytics-app.adoc
The menu entry was not updated to reflect the current location in the
tutorials page. This change makes the sparkpi top-level document conform
to the other tutorials.
=> update menu for sparkpi main page

tutorials.md
the entry on the tutorials page is missing this label.
=> add scala badge to sparkpi description

Gemfile, Gemfile.lock
This is in response to a warning from github about the jekyll version.
It has been updated and the gemfile.lock regenerated.
=> update jekyll version

CONTRIBUTING.md
This is to help newcomers better understand the process we have for
accepting changes.
=> add review standards section to contributing doc

get-started.adoc
The instructional commands should be contained in our "how do i"
documents. This allows us the the maximum re-use of the modular doc
format and also reduces the number of places we need to maintain when
updating instructions.
=> remove oc command from get started

_templates/presentation.adoc, community.html
This change adds the feature for having multiple presentation urls in a
presentation entry.
changes
* update community template to process multiple urls
* update community template to add some spacing between links
* update all presentations with new link format
* update presentation template
=> add multiple media links for presentations

_presentations/spark-for-library-developers-sseu-2018-part-1.adoc, _presentations/spark-for-library-developers-sseu-2018-part-2.adoc
This adds a local PDF of the slides for "Apache Spark for Library Developers."
Fixes #285.
=> adds local PDF of slide deck for eje/willb SAIS EU talk

_howdoi/use-spark-configs.adoc
This makes the examples at the end more explicit about what they are
affecting.
=> update how do i use spark configs document

_data/spark.yaml, openshift/README.md, openshift/resources-v0.5.6.yaml
Because resources.yaml contains configmaps and imagestreams
for spark that align with major.minor versions, it needs to
be revved when we change the spark major or minor version.
This change archives the previous resources.yaml for v0.5.6
and updates the top-level resources.yaml to reference spark 2.4.
=> Update resources.yaml for spark 2.4
